name: ${project.build.finalName}
main: com.i0dev.Reclaim.Heart
version: ${project.version}
author: i01
description: This plugin allows users to reclaim something based off of their rank.
website: ${project.url}
softdepend:
  - PlaceHolderAPI
depend: []
commands:
  Reclaim:
    aliases:
      - reclaims
    description: The main command for ${project.build.finalName}
    usage: /reclaim <help/reload/reset/remove>
permissions:
  Reclaim.reload.cmd:
    description: Reload config
    default: op
  Reclaim.base.cmd:
    description: Reclaim base - to actually claim the rewards
    default: not op
  Reclaim.reset.cmd:
    description: Resets all the reclaim data.
    default: op
  Reclaim.remove.cmd:
    description: Removes a user from status of being claimed.
    default: op